### ISSUE TITLE
integrate travis with serverless framework

### ISSUE THREAD

**Issue by Annnnnieee** [ubclaunchpad/census#12]
Done criteria:
* configured in serverless framework
* travis builds the projects and runs tests on every pr.
* aws is updated with most recent code upon merge automatically

**Comment by Eric1015** [comment]
@Annnnnieee 
Are we shifting from CircleCI to Travis?

**Comment by Annnnnieee** [comment]
@Eric1015 Yeah we are. We can't use CircleCi unless we get org authorization and LP is worried about having to manage too many authorized github apps, so we're just sticking with travis.

**Comment by r614** [comment]
Yeah

> @Annnnnieee
> Are we shifting from CircleCI to Travis?

Yeah!
